AWSTemplateFormatVersion: 2010-09-09
Description: DynamoDB tables to use as the datastore

Resources:
  ListsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "Id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "Id"
          KeyType: "HASH"

  ItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "ListId"
          AttributeType: "S"
        - AttributeName: "Id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ListId"
          KeyType: "HASH"
        - AttributeName: "Id"
          KeyType: "RANGE"

Outputs:
  ListsTableArn:
    Value: !GetAtt ListsTable.Arn
    Export:
      Name: !Sub "${AWS::StackName}:ListsTableArn"
  ListsTableName:
    Value: !Ref ListsTable
    Export:
      Name: !Sub "${AWS::StackName}:ListsTableName"
  ItemsTableArn:
    Value: !GetAtt ItemsTable.Arn
    Export:
      Name: !Sub "${AWS::StackName}:ItemsTableArn"
  ItemsTableName:
    Value: !Ref ItemsTable
    Export:
      Name: !Sub "${AWS::StackName}:ItemsTableName"
