name: Go

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: make deps

      - name: Build
        run: make build-lambda.zip

      - name: Test
        run: make test

      - name: Package
        run: make lambda.zip

      - name: Deploy
        run: aws lambda update-function-code --function-name ${{ secrets.FUNCTION_NAME }} --zip-file fileb://lambda.zip
        if: github.ref == 'refs/heads/main'
